### ISSUE TITLE
"flatMap is not a function" when attempting to build

### ISSUE THREAD

**Issue by Herteby** [Lattyware/elm-fontawesome#3]
Seems like my version of Node doesn't have Array.prototype.flatMap
Node v 10.3.0
NPM v 6.1.0

I see you have Babel, but maybe the config should be updated?

**Comment by Lattyware** [comment]
Yeah, I took a look - you should be able to fix with an import of `import "core-js/fn/array/flat-map";` rather than `lodash` - I'm adding a build that'll test other versions to keep us honest, although it's currently blowing up on the private packages.

Yeah, the new version of Elm took a long time to come around, but the ability to minify so effectively is really useful, especially in cases like this.

**Comment by Lattyware** [comment]
OK, there is now a working build testing we can get compilable Elm output on node versions 6, 8, 10 and 11, and there is actually a nicer fix than the one I mentioned - there is a `shippedProposals` setting for Babel that allows it to insert the `flat-map` polyfill as needed, so no need to add it in manually.
